### ISSUE TITLE
Job cleanup after restart

### ISSUE THREAD

**Issue by digitalfox** [enioka/jqm#158]
When engine start after a crash (example a beautiful outofmemory), every running or attributed job instance should be marked as crashed. 
Particulary annoying when the job is an highlander, it prevents any other launch.
Workaround : delete according line in jobinstance table.

**Comment by marcanpilami** [comment]
Weird. All RUNNING instances should be removed at startup by method JqmEngine.purgeDeadJobInstances at https://github.com/enioka/jqm/blob/master/jqm-all/jqm-engine/src/main/java/com/enioka/jqm/tools/JqmEngine.java#L351

What was the status inside the JobInstance table? (or even better: could you reproduce this with a test case?)
