### ISSUE TITLE
Horizontal scrollbar hide job line

### ISSUE THREAD

**Issue by digitalfox** [enioka/jqm#161]
When launching new job from admin gui, the "runs" table is automatically filtered on "active" jobs. When only one job is display (the one we just launched) an awful horizontal scrollbar hide this job.
This bug only applied in Chrome (39). Everything is ok with Firefox (33.1).

**Comment by marcanpilami** [comment]
https://github.com/angular-ui/ng-grid/issues/808 seems to be the root

**Comment by marcanpilami** [comment]
Removing from release 1.2.2. Will not be ocrrected in ng-grid, but should disappear by itself during ng-grid upgrade to the new version named ui-grid. This upgrade will be done in a future version - when ui-grid is out of beta.

**Comment by marcanpilami** [comment]
As it matters, the ugly workaround contained in 1bd4fc0d4d8c89e6c74143c00aab501c6c54c53e hides (quite literally) the issue. The underlying bug remains though, but the user impact is now much lower.

This makes (future) ui-grid migration a low priority point (as long as browser support remains OK in current ng-grid).

**Comment by marcanpilami** [comment]
ui-grid migration ticket is at #192

**Comment by marcanpilami** [comment]
Closed during    #192 work.
