### ISSUE TITLE
Modifications API impressions

### ISSUE THREAD

**Issue by zoubairdjerbi** [enioka/jqm#175]
Bonjour,

Pouvez -vous
1*/
Ajouter l'attribut RequestingUserName au PrintRequestAttributeSet (en plus du JobName)
cf. ligne 87 de com.enioka.jqm.providers.PrintServiceImpl
cf. : javadoc http://docs.oracle.com/javase/6/docs/api/javax/print/attribute/Attribute.html
2*/ Corriger afin de ne pas avoir en dur "houba"

class PrintServiceImpl implements PrintService
{
    PrintServiceImpl()
    {
        // This is package-private constructor.
    }
    @Override
    public void print(String printQueueName, String jobName, InputStream data) throws PrintException
    {
        print(printQueueName, "houba", data, DocFlavor.INPUT_STREAM.AUTOSENSE);
    }

Merci

**Comment by marcanpilami** [comment]
Bug part - should not use the default value when a value is provided.

Enhancement part - ad an attribute. Retain compatibility (add an overload).

OK to implement both in the next maintenance release.
