### ISSUE TITLE
JMX monitoring does not report engine down in some cases

### ISSUE THREAD

**Issue by digitalfox** [enioka/jqm#176]
The engine died with the following last words: 
23/03 11:39:34.126|WARN |INTERNAL_POLLER;polling orders;         |AbstractLifeCycle|FAILED org.eclipse.jetty.server.Server@70ac70ac: java.lang.OutOfMemoryError

And the monitoriing through JMX does not report this behaviour. For information, previously in this day, the web also crashed with outofmemory.

**Comment by marcanpilami** [comment]
OOM are tricky beasts, as themselves cannot be caugth. But I'm slightly distrubred by the absence of alert with a non-functioning node.
Exactly how was the node failing? No web UI, jobs not taken, jobs stuck in ATTRIBUTED... ?

Are you sure the JMX monitoring was failing? Should a node not poll for whatever reason, an alert should be visible. It may be the JMX system was fully down - could you check your monitoring history for lapses in monitoring data?

**Comment by digitalfox** [comment]
UI was ok  but indeed, log grabbing reported node dow. Job was in RUNNING 
state.

In fact, I don't make a JMX call by myself. I relied on our zabbix system that 
use the zabbix-jqm agent. 
Digging in zabbix-jqm-agent, I see socketexception.

-- 
S�bastien

**Comment by digitalfox** [comment]
Agent stack trace : 
java.net.SocketException: Broken pipe
at java.net.SocketOutputStream.socketWrite0(Native Method)
at java.net.SocketOutputStream.socketWrite(Unknown Source)
at java.net.SocketOutputStream.write(Unknown Source)
at org.oxymores.monitoring.ZabbixClientThread.run(ZabbixClientThread.java:153)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
java.net.SocketException: Broken pipe

**Comment by marcanpilami** [comment]
If I understand correctly, Zabbix could not ask for JMX data anymore. Perfectly understandable given the type of error.

But in that case, would you agree this is not a JQM bug? It was the responsibility of Zabbix to report it could not fetch the engine status anymore. And the OOM is not a JQM issue either - batch programs using too much memory will always end that way in a Java world...

**Comment by digitalfox** [comment]
Indeed, its looks like a jqm-zabbix-agent issue. Not a jqm issue.

**Comment by marcanpilami** [comment]
Closing as invalid then.
