### ISSUE TITLE
/tmp/jqm directory owner issue when running multiple instance of JQM with different users on single OS

### ISSUE THREAD

**Issue by digitalfox** [enioka/jqm#189]
Issue is for local webserver copy of files downloaded from remote node. Currently path is java.io.tmpdir + "jqm" + UUID.
The sudir /tmp/jqm is created by the first node with its own perms and owner. The subsequent nodes failed to write in this dir except if ugly chmod 777 is done.

**Comment by digitalfox** [comment]
Simple fix is to simply use java.io.tmpdir + UUID. It could be an issue from a security point of view (as it is today).  So we may use $JQM_HOME/tmp instead.

**Comment by marcanpilami** [comment]
The case is, the web services application has no idea where JQM_HOME is - it is designed to work even when run on Tomcat or other servlet container. (with a few functionalities missing). This is why tmpdir was used... This is not an edge case, as it is heavily used during dev. 

This also an issue with the tmpdir_UUID solution - as we don't know the UUID of the any 'local engine', we would recreate a new directory on every restart. Ugly. 

Perhaps the solution is simply to set restrictive permissions and write directly inside tmpdir. But Java 6 does not know how to set perms... so the current way, that is trusting the mask on Unixes, is the only one.

But I agree this is an issue, we need to change this. Adding it to the next release backlog.

**Comment by digitalfox** [comment]
So keep it in /tmp. Reading Java 6 doc about java.io.File.createTempFile() does not clearly indicates if rights are properly set or not. But name is predictable (bad random).
How about simple $HOME/.jqm/ ? That's private and distinct for each unix user.

**Comment by marcanpilami** [comment]
Well, actually we do not use createTempFile because it only destroys the file at the end of the JVM. As a JQM server is a long running process, it would mean creating a lot of temp files. 

JQM actually uses a specific FileStream wrapper that destroys the file when the stream is closed. So the normal default permissions apply.

I'm not sure of the security issue you see - why would you want a random name?

**Comment by digitalfox** [comment]
Just thinking to use createTempFile because it mays use proper private default permissions. Of course, the feature deleteOnExit is useless. It does not prevent from explicitely deleting the file I you already do.

**Comment by digitalfox** [comment]
The issue about the name is only if you use default CreateTempFile name generation. ID used looks very predictable. But that's not a major issue and it seems to be fixed in Java 7 so...
