### ISSUE TITLE
add index on history

### ISSUE THREAD

**Issue by digitalfox** [enioka/jqm#218]
hi,

I am using the following sql request to monitor batch performance and feed an ElasticSearch instance. Could you please add an index on end_date and applicationname ? An index already exist on applicationname (called hist_application). So the end_date column could be added to this one if you wish.
ps : i use end_date as filtering criteria because this is only way to get finished job in a monotone order.

**Comment by marcanpilami** [comment]
I'm afraid you've forgotten to include the "following query" ;-)

If this is a query on the History table, there are actually no indices out of the box (save the PK), but you are free to add your own. See http://jqm.readthedocs.io/en/jqm-all-1.3.6/admin/history.html for more details.
