### ISSUE TITLE
Why not use the REST web service?

### ISSUE THREAD

**Issue by schuettec** [enioka/jqm#221]
We plan to use JQM for our batch processes. We already have a UI application that enables us to manage everything. I would like to build a client that extends our UI to manage queues and queue mappings for JQM. However the documentation gives me a warning saying "the admin REST web service is a private JQM API. It should never be accessed directly."

Is there any reason why I should avoid using the REST API?

**Comment by schuettec** [comment]
Okay I found the chapter in the docs. Sorry!

Closed.

**Comment by marcanpilami** [comment]
I like it when tickets close by themselves ;-). The real reason behind the "closed API" thing is that we wanted to testproof it before with our own UI and our own command line. The command line is still being built. If you are ready to see a few things break with future version 1.4 (end of summer if everything goes well), feel free to use the admin REST API - it will become official at that point.

**Comment by ajithc16** [comment]
Can you please share some java swing application examples codes with complete imports that creates a job definition and enqueue the job?
