### ISSUE TITLE
Idea: Why not use MavengroupId:artifactId:version

### ISSUE THREAD

**Issue by schuettec** [enioka/jqm#222]
I'm currently checking out the features of JQM and I like the architecture and how easy it is to scale the cluster with additional nodes. As I studied the docs and played around with queues and jobs I found out that I always have to place a JAR into the jobs/ folder of JQM to deploy the classes. At this point you use Maven to download the transitive dependencies of the deployed JAR.

In our system we have a Maven Repository (Nexus) right in place to host our artifacts. Our JQM jobs are released to this Nexus too. It would be a nice feature if I only have to specify the groupId, artifactId and version to JQM to deploy my job implementations. I think that this is the minimum information JQM needs to deploy my JARs isn't it?

**Comment by marcanpilami** [comment]
To see if I understand you correctly: do you mean 
* replacing the whole deployment descriptor by just the Maven coordinates (in this case, we loose the ability to specify the job tags and other classifiers beforehand, and, more annoying, the ability to specify the class to run - it will have to be an executable jar with manifest. Other solution: specify everything afterwards though UI/CLI - the disadvantage here being that the deployment has to be scripted to become repeatable in multiple environments)
* A variant of the previous point were we add a few items (custom plugin) in the pom.xml allowing us to specify fully the deployment descriptor inside the pom (but in that case, what do we do for pom.xml without this plugin?)
* allowing the deployment descriptor to specify dependencies with corrdinates (which would be useful if the dev is not using Maven for build, therefore no pom.xml)
* something else my limited imagination does not let me see

I'm of course open to mix.

**Comment by schuettec** [comment]
Okay I hope this makes it clearer: I do not mean to replace the deployment descriptor. I mean replacing the field "Path to Jar" by Maven coordinates. I'm sorry but I didn't understand the other solution you mentioned. What do you mean with scriptable?

I think of a deployment descriptor where we can specify (as a alternative for "path to Jar") the maven coordinates. Then JQM accesses the Nexus defined in its global configuration and will get all the information it needs for downloading the single job implementation plus all of its transitive dependencies that are declared in the pom (that it accessible through the very same coordinates).

**Comment by marcanpilami** [comment]
So it really was something I had not imagined. Easy to do, immediate benefit => added to backlog.

Quick spec:
* a new "pathType" item is added to the descriptor. It is optional. If not given, a value of "FS" is assumed to keep ascending compatibility.
* when "pathType" is "FS", the "path" item is interpreted as a local file system path
* when "pathType" is "maven", the "path" item is interpreted a Maven coordinates.

Note that should a SNAPSHOT version be given inside "path", the standard Maven evaluation policy will occur (it will only be refreshed from time to time). This policy is set in Maven's settings.xml (and it is possible to specify another settings.xml file with the mavenSettingsFile global parameter).

Seems right to you?

**Comment by schuettec** [comment]
Wow absolutely yes!

Am 15.07.2016 4:20 nachm. schrieb "marcanpilami" <notifications@github.com>:

**Comment by marcanpilami** [comment]
Doc at http://jqm.readthedocs.io/en/1.4.1/jobs/packaging.html#pure-maven-package
