### ISSUE TITLE
Initial steps/script required for using MySQL for JQM 

### ISSUE THREAD

**Issue by paribhandari** [enioka/jqm#228]
Hi,

I changed the db settings to use mysql with jqm (as per the documentation). After that when i start the service i am getting below error. I think the tables need to be created. Could I get a script for the table, key creation?

aused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jqm.node' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

Thankyou
Pari

**Comment by marcanpilami** [comment]
Hi, I'm afraid you may have missed a step in the documentation. Ater settings up the database, you need to create the first node with `./jqm.sh (or ./jqm.ps1) createnode`. This takes care of the initialization of the database. (see http://jqm.readthedocs.io/en/jqm-all-1.3.7/admin/install.html#linux-unix for more details).

Also, if using MySQL, please take care to use version 1.3.7 as it fixes a nasty bug on first boot.

**Comment by paribhandari** [comment]
Thankyou for the quick response. Will check it out and upgrade the version. Regards,Pari
