### ISSUE TITLE
Notify the program which enqueued the request on completion

### ISSUE THREAD

**Issue by paribhandari** [enioka/jqm#229]
Hi,

Is there an exisiting way in which the JQM will notify the client (which had placed the request on the JQM queue) once the job is processed?
Or does the client needs to keep polling for the status?

TIA
Pari

**Comment by marcanpilami** [comment]
Hi,

there is no generic notification system. We have a long term ticket (#74) dealing with events and notifications. The idea would be to have interceptors receive events and do something with them. Such as calling a callback web service on your web server... However, this work is not currently scheduled, and would require either a motivated contributor or a sponsor to come to life.

In the meantime, we do have one existing specific notification: JQM can send a mail to an address (specified in the execution request) at the end of the run. It way be enough, depending on your use case.

MA

**Comment by paribhandari** [comment]
Thanks for the response.

**Comment by marcanpilami** [comment]
Closing - please reopen if the answer needs further clarification.
