### ISSUE TITLE
Hibernate Api Client : Error in Query.run (SQL IN Clause 1000 limit)

### ISSUE THREAD

**Issue by anissofiane** [enioka/jqm#239]
[LOG_GEP-15407.txt](https://github.com/enioka/jqm/files/657271/LOG_GEP-15407.txt)
om.enioka.jqm.api.JqmClientException: an error occured during query execution
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
java.sql.SQLSyntaxErrorException: ORA-01795: le nombre maximum d'expressions autorisé dans une liste est de 1000

**Comment by marcanpilami** [comment]
Thank you for the report. To confirm: are you doing a query which is expected to return a lot of results ? Is it only on history?

Also, if you add .setPageSize(999) to your query, does it work? I believe it is actually a mistake to try to return all the history through the Query API.

**Comment by anissofiane** [comment]
The query is expected to return all ended jobs for a day whithout pagination.
                
                Calendar from = Calendar.getInstance();
		from.add(Calendar.DATE, -1);
		
		Query q = Query.create().setEnqueuedAfter(from);
				
		q.setJobDefApplication(filters.get(APPLICATION));
		
		if (State.valueOf(filters.get(STATUS)) == State.ENDED) {
			q.addStatusFilter(State.ENDED);			
		} else if (State.valueOf(filters.get(STATUS)) == State.CRASHED) {
			q.addStatusFilter(State.CRASHED);			
		} else {
			q.addStatusFilter(State.RUNNING);
			q.setQueryLiveInstances(true).setQueryHistoryInstances(false);
		}
		
		if (Util.checkNotEmpty(filters.get(USER))) {
			q.setUser(filters.get(USER));
		}
		
		if (Util.checkNotEmpty(filters.get(AGENCY))) {
			q.setInstanceKeyword1(filters.get(AGENCY));
		}
		
		if (Util.checkNotEmpty(filters.get(TYPE))) {
			q.setApplicationName(filters.get(TYPE));
		}

**Comment by marcanpilami** [comment]
I see. Why cannot you actually use pagination? More than a thousand job instances is huge - it is not something you actually can display in a list. Note that I'm not trying to say you should never use the API that way - just trying to understand the actual need, so as to better answer it.

**Comment by marcanpilami** [comment]
The query API has been slightly tweaked for your needs. It should now be possible to retrieve a huge count of results through the API. Note that it WILL be slow if you fetch too many results - so you have to explicitly set the page size to null if you really want to do it.

**Comment by marcanpilami** [comment]
After talking with @anissofiane : use of Query.setApplicationName(List<String>) is what he actually needs, rather than getting all job instances and only then filtering in memory.

As the "more than 1000" bug is also corrected, closing this ticket.
