### ISSUE TITLE
Invalid maven optional dependency handling

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#243]
Hello!

We use mapstruct in our project. 
http://central.maven.org/maven2/org/mapstruct/mapstruct-jdk8/1.1.0.Final/mapstruct-jdk8-1.1.0.Final.pom contains optional dependency to mapstruct-common lib, which doesn't exist in repositories (seems that it is obsolete dependency). 

However, JQM handle optional dependency as required dependency and try to download it.
As mapstruct-commons does not exist, JQM fail to resolve dependency, and job crashed.

But, it should ignore absence mapstruct-common, because it an optional dependency and not required to job execution.

**Comment by marcanpilami** [comment]
Hi,

I've tried to reproduce the bug without success. I have created an integration test using 

```
                <dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>1.1.0.Final</version>
		</dependency>
```

And I use the Maven resolver. It correctly finds that there are no dependencies to load. 

Could you please set your node to TRACE log level (in the admin UI, go to Node tab, change the level, then restart your node) and post the log?

Also, could you check the version of JQM you are using?

Thanks, Marc-Antoine.

**Comment by echipachenko** [comment]
Hello!
I attached log file for crashed job.
Try to reproduce again with next dependency :
`
<dependency>
    <groupId>org.mapstruct</groupId>
    <artifactId>mapstruct-jdk8</artifactId>
    <version>1.1.0.Final</version>
</dependency>
`


[log.txt](https://github.com/enioka/jqm/files/850229/log.txt)

**Comment by marcanpilami** [comment]
Thanks for the log. WIth the exact same dep, it works. Could you please give me 
* the JQM version (at the start of the log)
* the result of `mvn dependency:tree` for your job?

**Comment by marcanpilami** [comment]
Perfect repro, thanks! Also, I had not understood you were using gradle, so obviously shade is not used. I've found the issue. Since you are using a uber-jar, all files from your libs are copied, including Maven technical files if the lib was created with Maven. So basically JQM finds the pom.xml that comes from the lib and uses it as if it were the pom.xml of your project. Which won't work as you've discovered.

I'll push a fix. In the meantime, you can simply disable the Maven feature by creating an empty "lib" directory in the same directory as your jar file.

**Comment by echipachenko** [comment]
ok, Thank you!

**Comment by marcanpilami** [comment]
After discussing it with the team, the real issue in your case is that you are creating an invalid Maven artifact. I know you do not care about Maven, but that is the result of your command. And sadly, the java Gradle plugin does leave a way to identify if it has uberified anything. 

So for a real production solution, I would suggest yo add a rule to your gradle build :
```
jar {
    from {configurations.compile.collect { it.isDirectory() ? it : zipTree(it)}} { 
            exclude "META-INF/maven/**"
    }
}
```

That way, all maven metadata will be removed from the resulting uber-jar.

Please note that you will still need to have a "lib" directory in the same directory as the jar - JQM considers it an error if it has no library source (but of course, the directory can be empty).

Do you consider this an appropriate resolution? If yes, I'll keep the ticket open to remind us to add a warning in the documentation.

**Comment by echipachenko** [comment]
Yes, it is resolution. I checked it and it works. Thanks.

**Comment by marcanpilami** [comment]
You are welcome. Glad to be of assistance.
