### ISSUE TITLE
XML Job definition issue

### ISSUE THREAD

**Issue by jcdugas** [enioka/jqm#244]
JQM Job definition integration doesn't trim XML tag content, leading to NoClassDefFounError on <javaClassName/> property when indentation is moving closing XML tag on the next line.

**Comment by marcanpilami** [comment]
It's actually a feature, not a bug (I always wanted to write this, sorry) at least for most fields. You are free to put whatever text, including carriage returns, in your strings, so we do not trim anything.

Now, it is true that we have applied the same logics to fields that obviously cannot have spaces or new lines. The following fields will be trimmed in next release: 
* name of the job definition (string)
* name of the default queue
* path to jar file
* path type
