### ISSUE TITLE
Enqueue at HOLD status

### ISSUE THREAD

**Issue by marcanpilami** [enioka/jqm#255]
New API: ```JobRequest.startPaused()```

A job requets using this API will be enqueued in the HOLD status.

**Comment by marcanpilami** [comment]
Done in 7d4dc8daa4f7d4d9ffafcc0f7399eeb0c066bd23

**Comment by shilpa0109** [comment]
@marcanpilami :

I cannot see this API (JobRequest.startPaused) in the version 2.2.1

 <dependency>
            <groupId>com.enioka.jqm</groupId>
            <artifactId>jqm-all</artifactId>
            <version>2.2.1</version>
        </dependency>

Can you guide me if I am doing anything wrong here.
