### ISSUE TITLE
JqmClientException when try to pause queue

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#285]
When I call jqmClient.pauseQueue(q) a JqmClientException was throw.

`com.enioka.jqm.api.JqmClientException: an internal JQM client exception occured
	com.enioka.jqm.api.JerseyClient.pauseQueue(JerseyClient.java:856)
	com.frontier.job.core.service.JobManagerJqmAdapter.lambda$hold$11(JobManagerJqmAdapter.java:396)
.....`

Root cause:
`
java.lang.IllegalStateException: Entity must not be null for http method PUT.
	org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:145)
	org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:97)
	org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:90)
	org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:412)
	org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:306)
	com.enioka.jqm.api.JerseyClient.pauseQueue(JerseyClient.java:848)
.....
`

same for clearQueue

**Comment by marcanpilami** [comment]
Three consecutive bugs on the WS client are three too many. The integration tests on the client had been removed during refactoring (those were the only tests removed) for various reasons which prove wrong today - these tests have therefore been reactivated. This should ensure better & more consistent WS client quality beginning today. 

New snapshot was uploaded.
