### ISSUE TITLE
Priority is always null

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#287]
Hi!
Priority field is always null in JobInstance, when get it from JqmClient.getJobs();

**Comment by marcanpilami** [comment]
Priority is only available for waiting & running job instances. We do not keep this information for past jobs.

**Comment by echipachenko** [comment]
Hi! I checked priority for active jobs (jqmClient.getActiveJobs()), and it also null. Could you please add information about priority for waiting & running job instances? And it would be great, if you add it for any job instance (running/completed/etc...).

**Comment by marcanpilami** [comment]
Actually this is from my tests and works today:
```
        int i = JobRequest.create("MarsuApplication", "TestUser").submit();

        //////////////////////////////////
        // JI priority

        // No priority by default
        Assert.assertEquals(null, JqmClientFactory.getClient().getJob(i).getPriority());

        // Change it.
        JqmClientFactory.getClient().setJobPriority(i, 5);
        Assert.assertEquals(5, (int) JqmClientFactory.getClient().getJob(i).getPriority());
```

aren't you simply doing your query on job instances on which you have not set the query? By default there is no priority, which means default priority (platform dependent, so we cannot have a default value inside the request)

**Comment by marcanpilami** [comment]
Oh - and I agree this needs some doc. I'm just waiting for you know what to actually finish the release...

**Comment by echipachenko** [comment]
Oh! Yes, you are right! Forget by previous message.
Priority exist, when I get jobs via client.getActiveJobs().
Thank you! However, I asked our business analytics, do we really need information about priority in  completed jobs, and I'm waiting for answer....

**Comment by marcanpilami** [comment]
Then I'll be sure to consider adding it when the other matter is resolved. I'll keep this ticket open for this purpose then.

**Comment by echipachenko** [comment]
Hi! Priority information for complemented job is really important feature for us. From QA perspective we want use it for testing and profiling (compare job execution time with specific priority). We have too many tests, which test that specific job submitted with specific priority and executed with it (we make query for completed jobs, find it, and check all properties which we can check with expected result, including priority). 
Another important case: user want to see in job history, how much time was taken by job, and change priority configuration for next run. So, could you include this feature in next snapshot or release build?

**Comment by marcanpilami** [comment]
yes

**Comment by marcanpilami** [comment]
New snapshot pushed to OSSRH. Beware, DB model change without upgrade script.
