### ISSUE TITLE
Queue status field

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#290]
Hi! Cold you add _status_ field to the Queue object?
We want to see current queue status from jqm client api: 
` List<Queue> getQueues();`
Is queue paused or no.

**Comment by marcanpilami** [comment]
Hi,

the Queue object is purely a descriptor, meant to be used with enqueue. I would prefer not to add any overhead to it, not to change its usage. Would a isQueuePaused(int/Queue) verb do instead?

MA

**Comment by echipachenko** [comment]
Yes,  _isQueuePaused(int/Queue)_ is good for us, thanks

**Comment by marcanpilami** [comment]
New API is QueueStatus getQueueStatus(Queue)
