### ISSUE TITLE
JQM Exception was not logged

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#293]
Hi!
Please add logging for JQM exceptions on JQM node.
Sometimes we have server exceptions in access to jqm api, however they are not logged on JQM serve-side.

```
alf@EPUAKYIW2182:~/Downloads/jqm-2.0.0.20170804/logs$ grep -r 'DatabaseException' ./
alf@EPUAKYIW2182:~/Downloads/jqm-2.0.0.20170804/logs$
```

**Comment by echipachenko** [comment]
Hi again!
It's really important thing, because for reporting [previous issue](https://github.com/enioka/jqm/issues/292) i was need debug JQM and change JQM code to log exception stacktrace into console.
Thanks!

**Comment by marcanpilami** [comment]
A logger was added for all exceptions occurring inside the REST server application. All exceptions are logged at the INFO level as most exceptions should be mistakes made by the client (which are translated as JqmInvalidRequestException on the client side). This specific logger is named "RestClientException". New snapshot uploaded.
