### ISSUE TITLE
Add runAfter field to JobInstance

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#294]
Hi!
Please, add field **runAfter** from _jobRequest_ also to _JobInstance_.
We want iterate over job instances, find instance with specific runAfter date and work on it (kill,change, etc).
Currently we have not possibility to do it.

**Comment by echipachenko** [comment]
Hi! Do you have any updates or ETA?

**Comment by marcanpilami** [comment]
snapshot uploaded.
