### ISSUE TITLE
ClassLoader leak with openjdk 1.8

### ISSUE THREAD

**Issue by jcdugas** [enioka/jqm#302]
JQM seems to be leaking memory with openjdk 1.8. Heapdump is showing a finalization issue with a log4j ConsoleAppender that is referencing JQM ClassLoader.
![class histogram](https://user-images.githubusercontent.com/8058370/34199530-5d3a763c-e56e-11e7-8653-2d5d66d23ce4.png)
![dominator tree](https://user-images.githubusercontent.com/8058370/34199531-5d50ceaa-e56e-11e7-9712-42953b9fa286.png)
![leak suspect](https://user-images.githubusercontent.com/8058370/34199532-5d67993c-e56e-11e7-870b-5d66857839eb.png)

**Comment by digitalfox** [comment]
Thank you for your report. Could you please try the following to chek if the problem still happen:

- disable the Console Appender.
- upgrade to latest log4J lib release

**Comment by marcanpilami** [comment]
As Sébastien said. You are likely using the deprecated and unsupported log4j 1.x version, which is not compatible with Java 1.8. Please upgrade to log4j2 for java 1.8 support.

Note this is likely, but your data does not allow us to determine the actual cause of the class loader leak. You would have to check why the finalizers… are not actually finalized. Is the finalizer thread doing work at the time of the crash, or is there a finalizing deadlock?

**Comment by jcdugas** [comment]
The console Appender is JQM's, can't see how to disable it.

We will try to upgrade log4j, even if we don't expect that it will magically fix the leak.

This issue seems to be classloader related, and I see that the default mode for JQM classloader is Parent-First which is known to be harmfull for memory leaks (see [https://wiki.apache.org/commons/Logging/UndeployMemoryLeak](https://wiki.apache.org/commons/Logging/UndeployMemoryLeak)) with components deployment/undeployment. Changing this classloader resolution mode in Child-First could do the trick, what do you think about it ?

**Comment by digitalfox** [comment]
Does the issue still happen now that you upgrade your lib ?

**Comment by alexelgier** [comment]
I'm having a similar issue.
My job is using log4j 2.8
After every execution of the job I'm seeing this in the logs: 

> 15/02 14:25:00.941|INFO |DRTVJob;payload;1234                    |LoaderLeakCleaner|A JMX Mbean will be forcefully unregistered to avoid classloader leaks: org.apache.logging.log4j2:type=1385b3c6
15/02 14:25:00.941|INFO |DRTVJob;payload;1234                    |LoaderLeakCleaner|A JMX Mbean will be forcefully unregistered to avoid classloader leaks: org.apache.logging.log4j2:component=Appenders,name=console,type=1385b3c6
15/02 14:25:00.941|INFO |DRTVJob;payload;1234                    |LoaderLeakCleaner|A JMX Mbean will be forcefully unregistered to avoid classloader leaks: org.apache.logging.log4j2:component=StatusLogger,type=1385b3c6
15/02 14:25:00.942|INFO |DRTVJob;payload;1234                    |LoaderLeakCleaner|A JMX Mbean will be forcefully unregistered to avoid classloader leaks: org.apache.logging.log4j2:component=Loggers,name=,type=1385b3c6
15/02 14:25:00.942|INFO |DRTVJob;payload;1234                    |LoaderLeakCleaner|A JMX Mbean will be forcefully unregistered to avoid classloader leaks: org.apache.logging.log4j2:component=Loggers,name=com.netsol.ETLJobs.job.DRTVJob.DRTVJob,type=1385b3c6
15/02 14:25:00.942|INFO |DRTVJob;payload;1234                    |LoaderLeakCleaner|A JMX Mbean will be forcefully unregistered to avoid classloader leaks: org.apache.logging.log4j2:component=ContextSelector,type=1385b3c6

After a number of job executions, my JQM node crashes with OOM error.
I've tried setting the execution context to childfirst, but this did not fix the issue.
At the moment I'm considering trying another logging framework to see if the issue continues.

Any help would be appreciated.

Regards,
Alex

**Comment by alexelgier** [comment]
I've switched from Log4j2 to Logback and the issue seems to have been fixed.

**Comment by marcanpilami** [comment]
Closing as fixed - customer removed unsupported log4j version and everything went fine.
