### ISSUE TITLE
JQM scheduled cleanup

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#307]
Hi @marcanpilami ! 
Currently, we had about one million completed job instances.
I worry about it because JQM does not have any cleaning up mechanism.

We need some configurable cleaning tools: to clean job history, logs, etc.
It should be configurable like we need the possibility to change the schedule for cleaning.
For example: remove all jobs information older than a month, or half year, or one year, etc.

Also, it would be great to have something like job IDs rebuilt after cleaning up, to avoid integer type overflow.

What do you think about it?

**Comment by marcanpilami** [comment]
First, the maintenance of the "history" table is up to the user - index it, partition it, etc. however it pleases you (as our different users have very different uses of this table). See http://jqm.readthedocs.io/en/jqm-all-2.0.0/admin/history.html for details.

That being said, we used to have a job (named JqmHistoryPurge) which was doing a purge of the history table. I can clean it up and re-integrate it in the next snapshot.

As for int overflow, in MySQL it means two billion launches are possible. At one million per day, it means more than five years to reach the limit. Is that really a risk for you?

**Comment by echipachenko** [comment]
Hi @marcanpilami !
Yes, you right! Seems here no risk in int overflow.
Regarding cleanup job: now it clear, we will create such job!
Thank you!
