### ISSUE TITLE
Cannot copy logs when time filter is active

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#308]
Hi @marcanpilami !
I found some little bug: it's impossible to copy log from log-viewer when time filter is active.
When time filter is not active - everything is OK

**Comment by echipachenko** [comment]
Hi @marcanpilami 
I will recheck it on Monday. 
The issue was in text selection. 
Logs displayed correctly, but, I was can't select them. So, I can't select some part of logs and copy/paste it to somewhere. But, without time-filter everything is ok.

**Comment by marcanpilami** [comment]
Oh. Reproduced. That's weird indeed.

**Comment by echipachenko** [comment]
Hi @marcanpilami 
It's minor issue but it can embarrass our users :)
Thanks for cooperation!

**Comment by marcanpilami** [comment]
Keeping you posted: this is solved in 2.2 (the version after the upcoming one). Also solved: issue with horizontal scrolling in the same dialog.
