### ISSUE TITLE
Queue capacity changes is not affected without restart

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#310]
Hi @marcanpilami 
After changing queue max parallel instances on page 'Queue Mapping' we was not saw any effect without restart JQM. So, currently, to apply changes of max parallel instances we need to do JQM restart.

But, it's very hard to do it on the real environment.
Could you make some changes in code, to apply changes of max parallel instances in the queue immediately after saving?

**Comment by echipachenko** [comment]
Also, I saw, that it's also working without restart, but only after disabling and enabling queue in the queue mappings.

**Comment by marcanpilami** [comment]
Clear bug - this parameter is supposed to be applied without restart. Scheduling this ticket for next week.

**Comment by marcanpilami** [comment]
Snapshot uploaded. Sorry for the delay.
