### ISSUE TITLE
Exception when setRunAfter called for job without runAfter value

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#311]
Hi @marcanpilami 
I found some bug:

I have the job, submitted to the queue. The job is not running, just submitted (or on hold).
I want to set the 'runAfter' property for that job and an error was trowed. 

Currently, I can change 'runAfter' only for a job, which already has not null  'runAfter' value.

In case, when 'runAfter' was null, I can't change it.

Could you fix it and ad possibility to change 'runAfter' for any not executed job?

**Comment by marcanpilami** [comment]
I'm not sure I understand - setting runAfter is only interesting for a scheduled job (single time, not recurring). If you want to create a job with runAfter, the way to do it is simply to specify JobRequest.setRunAfter. What exactly is your use case?

**Comment by echipachenko** [comment]
Use-case next:
1. User submit the job (plain job, not cron, not schedule)
2. The Job stay in the queue due to no available capacity
3. User want to shift the job (to the next day for example) and want to set when job need to be executed ('run after' property).

Currently we do it with the next steps:
1. cancel submitted job
2. submit same job with 'run after' property

**Comment by marcanpilami** [comment]
I see. So I'll indeed add the ability to remove a JI from queue and Schedule it.
