### ISSUE TITLE
QueuePoller sometimes stops and ceases to work

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#313]
Hi @marcanpilami 
Sometimes, when DB server has been restarted, queue pooller ceases to work.
We can submit new jobs to the JQM, but, JQM doesn't want take it to execution.
All jobs stay in state 'SUBMITTED'.

In the same time, JQM web console continue working fine, after DB restart.

See logs in attachments
[jqm-ctco-orke.log](https://github.com/enioka/jqm/files/2210038/jqm-ctco-orke.log)

**Comment by marcanpilami** [comment]
Hi. Trying to qualify the "sometimes". Is it just after the db was restarted (and it may be still starting) or are you sure the db is ready to process queries when starting JQM?

**Comment by marcanpilami** [comment]
Disregard previous question. This is a bug in DB Failure handling with maria DB. Will fix.
