### ISSUE TITLE
Impossible to change queue for SCHEDULED job

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#314]
Hi @marcanpilami !

Right now it's impossible to change queue for scheduled job.

Could fix it?
Probably, its just change 
` queries.put("jj_update_queue_by_id", "UPDATE __T__JOB_INSTANCE SET QUEUE=? WHERE ID=? AND STATUS IN('SUBMITTED', 'HOLDED')");`
       

to

`
 queries.put("jj_update_queue_by_id", "UPDATE __T__JOB_INSTANCE SET QUEUE=? WHERE ID=? AND STATUS IN('SUBMITTED', 'HOLDED', 'SCHEDULED')");`

**Comment by echipachenko** [comment]
Hi @marcanpilami !
Are there any updates here?

**Comment by marcanpilami** [comment]
Oops, this one slipped under my radar. Yes, it would be logical to allow scheduled job instances to be switched from a queue to another, as we allow non-started job instances to do so. We would also need to update the GUI. I'll add it to 2.1.

**Comment by echipachenko** [comment]
Thanks @marcanpilami !
When we can expect release of 2.1?

**Comment by marcanpilami** [comment]
if all goes well, current target is end of August
