### ISSUE TITLE
Change message for job which was killed by user

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#320]
Hi @marcanpilami !

Please change message from
`throw new JqmKillException("This job" + "(ID: " + ji.getId() + ")" + " has been killed by a user");`
to
`throw new JqmKillException("This job" + "(ID: " + ji.getId() + ")" + " was ended by a user");`

**Comment by marcanpilami** [comment]
May I ask you why? It seems to me the existing message is a more explicit than just 'was ended' - a kill is a kill. Also, use of 'has been' is preferable as the user action still has conséquences.

**Comment by marcanpilami** [comment]
Let's go for "forcefully ended" then. I must say as logs are more admin-facing than user-facing, the political correctness of that message had never been evaluated (admins are tough right?) ;-)

**Comment by rontheunissen** [comment]
We need to include the word "ended" (because that's what it says on the screen where the user "ends" the job. How about "manually ended while in progress"?
