### ISSUE TITLE
MSSQL Support

### ISSUE THREAD

**Issue by ganeshdevp** [enioka/jqm#333]
Hi,

Is there support for MSSQL database ? Documentation says only MySQL, Oracle and other. But what about MSSQL ? 

Thanks,
Ganesh

**Comment by marcanpilami** [comment]
Hi,

MSSQL is not currently supported. Also, it is not on our roadmap. If you require MSSQL support, first option is to develop that support and create a PR - even if an additionnal database is costly for us to maintain, we would definitely accept that PR into the main branch. Second option would be to actually fund this evolution and have Enioka do it for you. Do not hesitate to say if you are interested in either options in this ticket or at contact@enioka.com .
