### ISSUE TITLE
It's not possible to run a job by New Launch Form in JQM 2.2.1

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#366]
It's not possible to run a job by New Launch Form in JQM 2.2.1
Job Name field too short and it's impossible to enter any job name.
Found in Firefox, same for Chromium.

![Screenshot at 10-26-34](https://user-images.githubusercontent.com/3613889/61200778-3d734280-a6eb-11e9-8e4b-732a4d056095.png)

**Comment by marcanpilami** [comment]
Indeed. To workaround the issue, please change tab and come back. It occurs only the first time.
