### ISSUE TITLE
Feature Request: add job runAfter parameter to JQM UI

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#369]
Hi @marcanpilami 
In JQM 2.1.0 it's no possible to see Run After parameter in JQM UI
Navigation: JQM UI->Runs->double click on some job.
Could you add this parameter to JQM UI?
Thanks

**Comment by echipachenko** [comment]
Hi @marcanpilami 
Any updates?

**Comment by marcanpilami** [comment]
Hi @echipachenko ! I've sent you a mail on that subject and others. We are currently evaluating the opportunity of a new 2.x release before 3.x.
