### ISSUE TITLE
JMX, not able to pull beans using jolokia

### ISSUE THREAD

**Issue by mylesw42** [enioka/jqm#386]
I'm attempting to use [jolokia](https://jolokia.org/reference/html/index.html) to pull beans out of the JVM instance running JQM, and I'm not having much success. I'm hoping it's a simple configuration setting that needs to be adjusted. Any help is greatly appreciated.

When the app starts, I notice this in the log:

> 07/02 10:33:36.967|INFO |JQM engine;;tomcat                      |JqmEngine        |JMX remote listener will not be started as JMX registry port and JMX server port parameters are not both defined
> 07/02 10:33:36.968|INFO |JQM engine;;tomcat                      |JqmEngine        |JMX management beans will not be loaded as JMX server port is null or zero

Using jolokia's API, I have determined that the only beans being registered with Tomcat are the following:

$ curl http://localhost:8779/jolokia/search/com.enioka.jqm:* -s | jq .
 
```
{
  "request": {
    "mbean": "com.enioka.jqm:*",
    "type": "search"
  },
  "value": [
    "com.enioka.jqm:name=jdbc/jqm,type=JdbcPool"
  ],
  "timestamp": 1580869802,
  "status": 200
}
```

I am not able to pull out any of the JMX tree as defined in the [documentation](https://jqm.readthedocs.io/en/latest/admin/jmx.html)

- com.enioka.jqm:type=Node,name=XXXX
- com.enioka.jqm:type=Node.Queue,Node=XXXX,name=YYYY
- com.enioka.jqm:type=Node.Queue.JobInstance,Node=XXXX,Queue=YYYY,name=ZZZZ

I am also able to see the JVM beans:

```
{
  "request": {
    "mbean": "java.lang:*",
    "type": "search"
  },
  "value": [
    "java.lang:name=Metaspace,type=MemoryPool",
    "java.lang:type=Runtime",
    "java.lang:type=OperatingSystem",
    "java.lang:type=Threading",
    "java.lang:name=Code Cache,type=MemoryPool",
    "java.lang:type=Compilation",
    "java.lang:name=G1 Young Generation,type=GarbageCollector",
    "java.lang:name=CodeCacheManager,type=MemoryManager",
    "java.lang:name=Compressed Class Space,type=MemoryPool",
    "java.lang:name=G1 Eden Space,type=MemoryPool",
    "java.lang:name=G1 Old Gen,type=MemoryPool",
    "java.lang:type=Memory",
    "java.lang:type=ClassLoading",
    "java.lang:name=G1 Old Generation,type=GarbageCollector",
    "java.lang:name=Metaspace Manager,type=MemoryManager",
    "java.lang:name=G1 Survivor Space,type=MemoryPool"
  ],
  "timestamp": 1580869625,
  "status": 200
}
```

**Comment by marcanpilami** [comment]
Hi, indeed it seems just a configuration issue. The doc you link to states that `By default, JQM does not start the remote JMX server and the JMX beans can only be accessed locally. To start the JMX remote server, two Node (i.e. the parameters of a JQM engine) parameters must be set: jmxRegistryPort (the connection port) and jmxServerPort (the port on which the real communicate will occur). If one of these two parameters is null or less than one, the JMX remote server is disabled.`

So just set the two ports (through the web UI) and restart JQM and all JMX beans should be available remotely.

**Comment by mylesw42** [comment]
@marcanpilami Thanks for the advice. We found where to set the JMX ports in the GUI and after a restart, we can see the beans. I noticed that these variables are set in the database. But I'd like to template it in a config file to it is part of our automated deployment. I don't see any documentation on how to do that. Is there a way? Thanks again!

```
{
  "request": {
    "mbean": "com.enioka.jqm:*",
    "type": "search"
  },
  "value": [
    "com.enioka.jqm:name=jdbc/jqm,type=JdbcPool",
    "com.enioka.jqm:Node=tomcat,name=QBATCH,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=CBATCH,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=LBATCH,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=DEFAULT,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=SNBATCH,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=QCTL,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=CTCBATCH,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=MONITORS,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=CTCMQ,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=AMSBATCH,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=TRICKLE,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=NBATCH,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=MQTALKQ,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=SATQUE,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=RPTQUE,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,Queue=DEFAULT,name=1361,type=Node.Queue.JobInstance",
    "com.enioka.jqm:Node=tomcat,name=AMS,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=SUNQUE,type=Node.Queue",
    "com.enioka.jqm:name=tomcat,type=Node",
    "com.enioka.jqm:Node=tomcat,name=SAIDS,type=Node.Queue",
    "com.enioka.jqm:Node=tomcat,name=SBATCH,type=Node.Queue"
  ],
  "timestamp": 1581714632,
  "status": 200
}
```

**Comment by marcanpilami** [comment]
Officially, there is no way to do this. On our backlog, we have a new CLI command `Set-Node`, which would allow to change all interesting nodes properties, as well as new arguments for the existing `New-Node` command. As neither we (the Enioka company) nor our current customers have much use for these, this is not currently very high in the backlog however. 

Now, there is an unsupported way. But as always in this case, this means your automated deployment scripts may have to change between versions. The CLI has an undocumented `Import-ClusterConfiguration` command which allows you to import an XML file containing a lot of configuration, including nodes. An example is [here](https://github.com/enioka/jqm/blob/master/docker/config/selfConfig.single.xml). We are using this internaly (along with also undocumented `Install-NodeTemplate`, which allows to copy nodes) to build our Docker images.

Another unsupported way would obviously to directly update the database. Same risks with new versions of course, and very much frowned upon (the database is so crucial to JQM that we cannot encourage users to go delve inside it).

Finally, shameless compulsory commercial plug: should you really need the new CLI commands, or official XML import APIs, do not hesitate to contact us either for dev or support contracts (contact@enioka.com).

**Comment by mylesw42** [comment]
Thanks @marcanpilami - We will take a look, and if we need this to be a supported feature for our environment, we will reach out.
