### ISSUE TITLE
logback.classic append lock seems to be JVM wide

### ISSUE THREAD

**Issue by simonwibberley** [enioka/jqm#392]
I'm running a Spring Boot application with a JQM provided context as per the docs. When running a scale test (100 runners) there was very high contention on a log appender stream which seems to be JVM wide. 

As I understand it, the logger prioritises ERROR level messages so a blocking is required. For logback, this blocking can be disabled with:
```xml
    <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <neverBlock>true</neverBlock>
        <appender-ref ref="CONSOLE" />
    </appender>
``` 

Is it possible this kind of lock break the classloader isolation JQM relies upon?

Please see stack trace attached.

[jqm.stack.zip](https://github.com/enioka/jqm/files/4312213/jqm.stack.zip)

**Comment by marcanpilami** [comment]
Hi. JQM itself does not use logback. It seems to me you are seeing contention on logs written by your own code isn't it?

If that is the case and you are using the supplied Spring runner context as per the docs: this means you are likely *not* using class loader isolation. This is the `<persistent>true</persistent>` of the deployment descriptor: the execution context is kept between launches for all job definitions which use the same context (the `<executionContext>MainSharedSpringContext</executionContext>` part of the deployment descriptor).

So you have (if my hypothesis are correct of course) only one CL. So your logback library is shared between all your launches, therefore the global lock.

If you want a persistent class loader (good for performances as it avoids multiple Spring context loadings) but isolate different class of job definitions, you can create different execution contexts. If you truly want every job instance to be fully independent, you'll likely have to disable context persistence, at a great performance cost (likely greater than what you loose on log contention, and you loose a lot of RAM this way, depending on what is loaded inside your Spring context).

**Comment by simonwibberley** [comment]
Thanks for your reply - I believe you are correct. Possibly it's something to comment on in the docs? From my perspective, I deployed JQM as recommended with a widely used logging framework and got surprising results. Possibly it's a niche use case? But it seems a really great way of using Spring Boot with JQM (which is also great in general FYI, thanks!) 

Feel free to close!

**Comment by marcanpilami** [comment]
Thanks for the compliment ;-)

I'm adding this to the doc to close the ticket:

Note that the following configuration assumes that you want to share the Spring context between different executions and potentially between different :def:`JobDef` to avoid initializing it on each run as it is often very costly. This means sharing the same class loader for all executions, which is not the JQM default. If this does not suit your needs, change the execution context ``<persistent>true</persistent>`` to false and the default JQM behaviour of having one different class loader per launch will be reinstated.

**Comment by simonwibberley** [comment]
Hi @marcanpilami - apols form reopening a ticket. But, could you provide some guidance on providing different execution contexts and keeping persistent class loader? 

Ideally, I would like to be able to differentiate jobs in JEF, reuse the same Spring context, but have difference execution contexts to separate the logger instances: is that possible? 

To address the JEF thing, would they have to have different applications? In that case, is it still possible to share the same Spring context but also have different execution contexts?


Also, is there a way to do this programmatically on the fly?

Many thanks,

Simon
