### ISSUE TITLE
ImportJobDef for long xml file error

### ISSUE THREAD

**Issue by ffayel** [enioka/jqm#395]
When trying to import an large job definition file. 
We are the following error:

`java.sql.SQLException: ORA-01000: maximum open cursors exceeded`

See attached fil for full error :
[error_import_xml_jobdef.log](https://github.com/enioka/jqm/files/4521824/error_import_xml_jobdef.log)
current run : JQM 2.2.3 on Oracle 12c database

**Comment by marcanpilami** [comment]
Could you please also give us the connection pool parameters ? The ones inside the xml configuration file.

**Comment by ffayel** [comment]
No change of Docker Conf default value : JQM_POOL_MAX : 10

`<resource
    name='jdbc/jqm'
    auth='Container'
    type='javax.sql.DataSource'
    factory='org.apache.tomcat.jdbc.pool.DataSourceFactory'
    testWhileIdle='true'
    testOnBorrow='false'
    testOnReturn='true'
    validationQuery='select 1 from dual'
    validationInterval='1000'
    timeBetweenEvictionRunsMillis='60000'
    maxActive='10'
    minIdle='2'
    maxIdle='5'
    maxWait='30000'
    initialSize='5'
    removeAbandonedTimeout='3600'
    removeAbandoned='true'
    logAbandoned='true'
    minEvictableIdleTimeMillis='60000'
    jmxEnabled='true'
    username='userr'
    password='passxww'
    driverClassName='oracle.jdbc.OracleDriver'
    url='URL'
    connectionProperties='v$session.program=JQM;'
    singleton='true'
/>`

I'm attached the jobDef xml
[jobdefxml.zip](https://github.com/enioka/jqm/files/4521950/jobdefxml.zip)

**Comment by marcanpilami** [comment]
Last question, what is your open_cursors parameter?

**Comment by ffayel** [comment]
Value is : Open_cursors = 300

**Comment by ffayel** [comment]
I see in CI.java (line : 200)  the ResultSet is not close! normaly ?

**Comment by marcanpilami** [comment]
Yes it is normal. Not very usual I know, but in JQM DbConn objects are supposed very short lived. They track all open result sets and close them just before they die to avoid any leak. In this case, of course, we see a limit of this approach (your configuration is entirely reasonable, we just open too many cursors/resultsets in this import).

While waiting for a fix, a workaround is to cut your file in two.

**Comment by ffayel** [comment]
Yes i cut for my test, but is a very long def. 
Waiting this fix for production usage.

**Comment by ffayel** [comment]
Hello, i added a other case. In this we have 5 files .xml. Unitarily everything is going well but if all the files are present same issue.
[docker-jobs_interfaces.zip](https://github.com/enioka/jqm/files/4540043/docker-jobs_interfaces.zip)

**Comment by marcanpilami** [comment]
Corrected in 2.2.4. I cannot add a test as Oracle auto tests were only introduced in 3.x, but your file was tested with max_cursors at 50 without issues.

**Comment by marcanpilami** [comment]
2.2.4 was released. Fixed in 76d532d321a2dcd52cae606ed977d58416ab7365.
