### ISSUE TITLE
GUI Issues in Jqm-2.2.4

### ISSUE THREAD

**Issue by RajeevKumarMarrapu** [enioka/jqm#397]
I found the following issues in jqm-2.2.4
1. The Job definitions tab in web admin console is not fully fitting into my desktop window ( see at bottom part of the screen)
![issue1](https://user-images.githubusercontent.com/25297104/81767491-2ad9bd80-94f6-11ea-91da-4eff2290a04d.PNG)

2. The issue mentioned in point one is also coming for users tab
![issue2](https://user-images.githubusercontent.com/25297104/81767193-6cb63400-94f5-11ea-8ff7-98e280d34a4a.PNG)

3. Some times the Job definitions tab is hanging and no other tabs are showing in the screen, page up and down are also not working
![issue3](https://user-images.githubusercontent.com/25297104/81767761-da169480-94f6-11ea-94c9-d6fd569168bd.PNG)

4. Some times after pressing logout button in home tab then its not showing the login screen

5. New launch form window is not cleared for each new launch of a job. previous job values are reappeared for new job launch

**Comment by marcanpilami** [comment]
The first points are a known issue - the jobdef form and user form are not fully responsive. As there is no ticket for that issue, we'll use this one to track it.

Point 4 requires investigation (and a dedicated ticket).

Point 5 is actually the desired behaviour. Some users want to be able to easily repeat their launches, simply changing one parameter and the like.

**Comment by RajeevKumarMarrapu** [comment]
@marcanpilami I have created the dedicated [ticket ](https://github.com/enioka/jqm/issues/398) for Point 4 mentioned above along with the reference

**Comment by RajeevKumarMarrapu** [comment]
@marcanpilami Similarly sometimes I'm unable to login too. I have created the [ticket ](https://github.com/enioka/jqm/issues/399 )for this too.

**Comment by marcanpilami** [comment]
Thanks, we'll have a look.

**Comment by RajeevKumarMarrapu** [comment]
@marcanpilami coming to fifth point in my business use case job to job the parameters are completely different. If I run the XXX job with some parameters then I want to launch the some YYY job, the previously launched parameters are reappeared for YYY job. So it would be better if you can implement a new button beside the "Add" parameter which clears all previous job parameters. something like below
![feature](https://user-images.githubusercontent.com/25297104/81901608-6b136b80-95dc-11ea-8f79-2742fcf1a23d.PNG)

**Comment by echipachenko** [comment]
Hi @marcanpilami 
Could you have some ETA for this?

**Comment by marcanpilami** [comment]
All points should be done now (2.2.5)
