### ISSUE TITLE
JQM 2.2.4 web console not showing login screen after pressing the logout button

### ISSUE THREAD

**Issue by RajeevKumarMarrapu** [enioka/jqm#398]
After successful login to jqm, if you are trying to logout from jqm web console then its not showing the login screen after pressing the logout button. Please find the below reference
![logout_issue](https://user-images.githubusercontent.com/25297104/81829752-dca9d600-9558-11ea-99a2-504d74be9fe5.gif)

**Comment by marcanpilami** [comment]
Fixed in 2.2.5
