### ISSUE TITLE
JQM 2.2.4 web console not showing home screen after pressing the login button with valid credentials

### ISSUE THREAD

**Issue by RajeevKumarMarrapu** [enioka/jqm#399]
Sometimes I'm unable to login to Jqm even though I'm giving valid login credentials but its not always the case. Please find the below reference
![login_issue](https://user-images.githubusercontent.com/25297104/81833015-d0c01300-955c-11ea-9c70-704f3a680821.gif)

**Comment by ffayel** [comment]
Same issue. Login request is ok but not redirect to history's page.

**Comment by marcanpilami** [comment]
Tentative fix (could not reproduce) in 2.2.5. Please reopen if needed.
