### ISSUE TITLE
JQM V2.2.5 adds running jobs to the JMX LateJobs

### ISSUE THREAD

**Issue by ModarHIJAZI** [enioka/jqm#413]
In version 2.2.5, we have found that the JMX "Latejobs" is returning the running jobs as if they are late even if ALERT_AFTER_SECONDS is configured as "null" in the database for those jobs:
![image](https://user-images.githubusercontent.com/47812096/94800302-ab855180-03e4-11eb-9a97-d939e4262e35.png)
Running jobs:
![image](https://user-images.githubusercontent.com/47812096/94800311-afb16f00-03e4-11eb-8988-c4cba0559b49.png)
ALERT_AFTER_SECONDS is configured as "null" :
![image](https://user-images.githubusercontent.com/47812096/94800715-467e2b80-03e5-11eb-9d49-70efef4789db.png)

**Comment by marcanpilami** [comment]
Thanks for reporting this very old bug - this poor functionality does not seem to receive much love from users. Fixed in v2, will be in next maintenance release.
