### ISSUE TITLE
Security Manager on JDK 17+

### ISSUE THREAD

**Issue by iherasymenko** [enioka/jqm#471]
JQM itself works fine on JDK 17; however, there's a warning with regards to the deprecated Security Manager.

https://openjdk.java.net/jeps/411

```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.enioka.jqm.tools.JqmEngine (file:/C:/home/projects/ctco-orke-frontier/frontier/job-service/jqm-launcher/build/jqm-2.2.8/lib/jqm-engine-2.2.8.jar)
WARNING: Please consider reporting this to the maintainers of com.enioka.jqm.tools.JqmEngine
WARNING: System::setSecurityManager will be removed in a future release
```

I am willing to spend some time on this and provide a code contribution, but it looks like there's nothing to do at this point of time since a new API for preventing calling `System.exit(...)` has not even been proposed.

**Comment by iherasymenko** [comment]
cc: @echipachenko

**Comment by unusual-thoughts** [comment]
Judging by the lack of comments in https://bugs.openjdk.java.net/browse/JDK-8199704, a replacement API isn't going to materialize any time soon

**Comment by marcanpilami** [comment]
That is indeed mightily annoying. Removing the security manager is going to be a pain in the ass for most application servers, we should first check what they are going to do...

**Comment by marcanpilami** [comment]
Well the JDK ticket is going nowhere and netbeans & other big security managers are simply working around the issue for now. So I have done the same and the JQM functionality to prevent `System.exit` is now disabled on Java 17+.

We should revisit this as soon as the JDK ticket is updated - ticket https://github.com/enioka/jqm/issues/475 was created for this.
