### ISSUE TITLE
Performances: add job pool (ready to fire jobinstances)

### ISSUE THREAD

**Issue by marcanpilami** [enioka/jqm#67]
Instead of a raw thread pool, create a job instance pool. A set of threads with:
* libraries already loaded
* classloader set
* just missing parameters + call start/run/main.

Pooling mechanism is to be discussed. Already of interest:
* max nb waiting per JobDef
* min nb waiting per JobDef (= initial size ?)
* max seconds waiting per JobDef + globally
* interceptors, which could be linked to #topen

**Comment by marcanpilami** [comment]
Closing. The cost would not be worth the complexity. This was demonstrated when remonving the thread pool (now we create a thread for each launch) - no perf hit, but simplifies everything (e.g. : no more thread local issues). This would not only require getting the thread pool back, but specialize it, so far too complicated for a simple tool.

**Comment by digitalfox** [comment]
100% agree !
